replicaCount: 1

global:
  namespace: "webapp"
  aws:
    region: "us-east-2"
image: 617850135881.dkr.ecr.us-east-2.amazonaws.com/prod-app:latest-21
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
