apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        jwt_secret: "{{`{{ .jwt_secret }}`}}"  # Escape Helm template for ESO
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: prod/jwt
        property: jwt_secret